#ifndef S21_ERRORS_H
#define S21_ERRORS_H

// макросы для определения операционной системы
#if defined(__APPLE__) && defined(__MACH__)
#define S21_MACOS 1
#define S21_LINUX 0
#define S21_MAX_ERROR_COUNT 107
#elif defined(__linux__)
#define S21_MACOS 0
#define S21_LINUX 1
#define S21_MAX_ERROR_COUNT 133
#endif

#if S21_MACOS
// сообщения об ошибках для macOS
static const char *s21_error_messages[] = {
    [0] = "Undefined error: 0",
    [1] = "Operation not permitted",             // EPERM
    [2] = "No such file or directory",           // ENOENT
    [3] = "No such process",                     // ESRCH
    [4] = "Interrupted system call",             // EINTR
    [5] = "Input/output error",                  // EIO
    [6] = "Device not configured",               // ENXIO
    [7] = "Argument list too long",              // E2BIG
    [8] = "Exec format error",                   // ENOEXEC
    [9] = "Bad file descriptor",                 // EBADF
    [10] = "No child processes",                 // ECHILD
    [11] = "Resource deadlock avoided",          // EDEADLK
    [12] = "Cannot allocate memory",             // ENOMEM
    [13] = "Permission denied",                  // EACCES
    [14] = "Bad address",                        // EFAULT
    [15] = "Block device required",              // ENOTBLK
    [16] = "Resource busy",                      // EBUSY
    [17] = "File exists",                        // EEXIST
    [18] = "Cross-device link",                  // EXDEV
    [19] = "Operation not supported by device",  // ENODEV
    [20] = "Not a directory",                    // ENOTDIR
    [21] = "Is a directory",                     // EISDIR
    [22] = "Invalid argument",                   // EINVAL
    [23] = "Too many open files in system",      // ENFILE
    [24] = "Too many open files",                // EMFILE
    [25] = "Inappropriate ioctl for device",     // ENOTTY
    [26] = "Text file busy",                     // ETXTBSY
    [27] = "File too large",                     // EFBIG
    [28] = "No space left on device",            // ENOSPC
    [29] = "Illegal seek",                       // ESPIPE
    [30] = "Read-only file system",              // EROFS
    [31] = "Too many links",                     // EMLINK
    [32] = "Broken pipe",                        // EPIPE
    [33] = "Numerical argument out of domain",   // EDOM
    [34] = "Result too large",                   // ERANGE
    [35] = "Resource temporarily unavailable",   // EAGAIN
    [36] = "Operation would block",              // EWOULDBLOCK
    [37] = "Operation now in progress",          // EINPROGRESS
    [38] = "Operation already in progress",      // EALREADY
    [39] = "Socket operation on non-socket",     // ENOTSOCK
    [40] = "Destination address required",       // EDESTADDRREQ
    [41] = "Message too long",                   // EMSGSIZE
    [42] = "Protocol wrong type for socket",     // EPROTOTYPE
    [43] = "Protocol not available",             // ENOPROTOOPT
    [44] = "Protocol not supported",             // EPROTONOSUPPORT
    [45] = "Socket type not supported",          // ESOCKTNOSUPPORT
    [46] = "Operation not supported",            // ENOTSUP
    [47] = "Protocol family not supported",      // EPFNOSUPPORT
    [48] = "Address family not supported by protocol family",  // EAFNOSUPPORT
    [49] = "Address already in use",                           // EADDRINUSE
    [50] = "Cannot assign requested address",                  // EADDRNOTAVAIL
    [51] = "Network is down",                                  // ENETDOWN
    [52] = "Network is unreachable",                           // ENETUNREACH
    [53] = "Network dropped connection on reset",              // ENETRESET
    [54] = "Software caused connection abort",                 // ECONNABORTED
    [55] = "Connection reset by peer",                         // ECONNRESET
    [56] = "No buffer space available",                        // ENOBUFS
    [57] = "Socket is already connected",                      // EISCONN
    [58] = "Socket is not connected",                          // ENOTCONN
    [59] = "Cannot send after socket shutdown",                // ESHUTDOWN
    [60] = "Too many references: cannot splice",               // ETOOMANYREFS
    [61] = "Connection timed out",                             // ETIMEDOUT
    [62] = "Connection refused",                               // ECONNREFUSED
    [63] = "Too many levels of symbolic links",                // ELOOP
    [64] = "File name too long",                               // ENAMETOOLONG
    [65] = "Host is down",                                     // EHOSTDOWN
    [66] = "No route to host",                                 // EHOSTUNREACH
    [67] = "Directory not empty",                              // ENOTEMPTY
    [68] = "Too many processes",                               // EPROCLIM
    [69] = "Too many users",                                   // EUSERS
    [70] = "Disk quota exceeded",                              // EDQUOT
    [71] = "Stale NFS file handle",                            // ESTALE
    [72] = "Too many levels of remote in path",                // EREMOTE
    [73] = "RPC struct is bad",                                // EBADRPC
    [74] = "RPC version wrong",                                // ERPCMISMATCH
    [75] = "RPC prog. not avail",                              // EPROGUNAVAIL
    [76] = "Program version wrong",                            // EPROGMISMATCH
    [77] = "Bad procedure for program",                        // EPROCUNAVAIL
    [78] = "No locks available",                               // ENOLCK
    [79] = "Function not implemented",                         // ENOSYS
    [80] = "Inappropriate file type or format",                // EFTYPE
    [81] = "Authentication error",                             // EAUTH
    [82] = "Need authenticator",                               // ENEEDAUTH
    [83] = "Device power is off",                              // EPWROFF
    [84] = "Device error",                                     // EDEVERR
    [85] = "Value too large to be stored in data type",        // EOVERFLOW
    [86] = "Bad executable (or shared library)",               // EBADEXEC
    [87] = "Bad CPU type in executable",                       // EBADARCH
    [88] = "Shared library version mismatch",                  // ESHLIBVERS
    [89] = "Malformed Mach-o file",                            // EBADMACHO
    [90] = "Operation canceled",                               // ECANCELED
    [91] = "Identifier removed",                               // EIDRM
    [92] = "No message of desired type",                       // ENOMSG
    [93] = "Illegal byte sequence",                            // EILSEQ
    [94] = "Attribute not found",                              // ENOATTR
    [95] = "Bad message",                                      // EBADMSG
    [96] = "EMULTIHOP (Reserved)",                             // EMULTIHOP
    [97] = "No message available on STREAM",                   // ENODATA
    [98] = "ENOLINK (Reserved)",                               // ENOLINK
    [99] = "No STREAM resources",                              // ENOSR
    [100] = "Not a STREAM",                                    // ENOSTR
    [101] = "Protocol error",                                  // EPROTO
    [102] = "STREAM ioctl timeout",                            // ETIME
    [103] = "Operation not supported on socket",               // EOPNOTSUPP
    [104] = "No such policy registered",                       // ENOPOLICY
    [105] = "State not recoverable",           // ENOTRECOVERABLE
    [106] = "Previous owner died",             // EOWNERDEAD
    [107] = "Interface output queue is full",  // EQFULL
};

#elif S21_LINUX
// сообщения об ошибках для Linux
static const char *s21_error_messages[] = {
    [0] = "Success",
    [1] = "Operation not permitted",                             // EPERM
    [2] = "No such file or directory",                           // ENOENT
    [3] = "No such process",                                     // ESRCH
    [4] = "Interrupted system call",                             // EINTR
    [5] = "Input/output error",                                  // EIO
    [6] = "No such device or address",                           // ENXIO
    [7] = "Argument list too long",                              // E2BIG
    [8] = "Exec format error",                                   // ENOEXEC
    [9] = "Bad file descriptor",                                 // EBADF
    [10] = "No child processes",                                 // ECHILD
    [11] = "Resource temporarily unavailable",                   // EAGAIN
    [12] = "Cannot allocate memory",                             // ENOMEM
    [13] = "Permission denied",                                  // EACCES
    [14] = "Bad address",                                        // EFAULT
    [15] = "Block device required",                              // ENOTBLK
    [16] = "Device or resource busy",                            // EBUSY
    [17] = "File exists",                                        // EEXIST
    [18] = "Invalid cross-device link",                          // EXDEV
    [19] = "No such device",                                     // ENODEV
    [20] = "Not a directory",                                    // ENOTDIR
    [21] = "Is a directory",                                     // EISDIR
    [22] = "Invalid argument",                                   // EINVAL
    [23] = "Too many open files in system",                      // ENFILE
    [24] = "Too many open files",                                // EMFILE
    [25] = "Inappropriate ioctl for device",                     // ENOTTY
    [26] = "Text file busy",                                     // ETXTBSY
    [27] = "File too large",                                     // EFBIG
    [28] = "No space left on device",                            // ENOSPC
    [29] = "Illegal seek",                                       // ESPIPE
    [30] = "Read-only file system",                              // EROFS
    [31] = "Too many links",                                     // EMLINK
    [32] = "Broken pipe",                                        // EPIPE
    [33] = "Numerical argument out of domain",                   // EDOM
    [34] = "Numerical result out of range",                      // ERANGE
    [35] = "Resource deadlock avoided",                          // EDEADLK
    [36] = "File name too long",                                 // ENAMETOOLONG
    [37] = "No locks available",                                 // ENOLCK
    [38] = "Function not implemented",                           // ENOSYS
    [39] = "Directory not empty",                                // ENOTEMPTY
    [40] = "Too many levels of symbolic links",                  // ELOOP
    [41] = "No message of desired type",                         // ENOMSG
    [42] = "Identifier removed",                                 // EIDRM
    [43] = "Channel number out of range",                        // ECHRNG
    [44] = "Level 2 not synchronized",                           // EL2NSYNC
    [45] = "Level 3 halted",                                     // EL3HLT
    [46] = "Level 3 reset",                                      // EL3RST
    [47] = "Link number out of range",                           // ELNRNG
    [48] = "Protocol driver not attached",                       // EUNATCH
    [49] = "No CSI structure available",                         // ENOCSI
    [50] = "Level 2 halted",                                     // EL2HLT
    [51] = "Invalid exchange",                                   // EBADE
    [52] = "Invalid request descriptor",                         // EBADR
    [53] = "Exchange full",                                      // EXFULL
    [54] = "No anode",                                           // ENOANO
    [55] = "Invalid request code",                               // EBADRQC
    [56] = "Invalid slot",                                       // EBADSLT
    [57] = "Bad font file format",                               // EBFONT
    [58] = "Device not a stream",                                // ENOSTR
    [59] = "No data available",                                  // ENODATA
    [60] = "Timer expired",                                      // ETIME
    [61] = "Out of streams resources",                           // ENOSR
    [62] = "Machine is not on the network",                      // ENONET
    [63] = "Package not installed",                              // ENOPKG
    [64] = "Object is remote",                                   // EREMOTE
    [65] = "Link has been severed",                              // ENOLINK
    [66] = "Advertise error",                                    // EADV
    [67] = "Srmount error",                                      // ESRMNT
    [68] = "Communication error on send",                        // ECOMM
    [69] = "Protocol error",                                     // EPROTO
    [70] = "Multihop attempted",                                 // EMULTIHOP
    [71] = "RFS specific error",                                 // EDOTDOT
    [72] = "Invalid message",                                    // EBADMSG
    [73] = "Value too large for defined data type",              // EOVERFLOW
    [74] = "Name not unique on network",                         // ENOTUNIQ
    [75] = "File descriptor in bad state",                       // EBADFD
    [76] = "Remote address changed",                             // EREMCHG
    [77] = "Can not access a needed shared library",             // ELIBACC
    [78] = "Accessing a corrupted shared library",               // ELIBBAD
    [79] = ".lib section in a.out corrupted",                    // ELIBSCN
    [80] = "Attempting to link in too many shared libraries",    // ELIBMAX
    [81] = "Cannot exec a shared library directly",              // ELIBEXEC
    [82] = "Invalid or incomplete multibyte or wide character",  // EILSEQ
    [83] = "Interrupted system call should be restarted",        // ERESTART
    [84] = "Streams pipe error",                                 // ESTRPIPE
    [85] = "Too many users",                                     // EUSERS
    [86] = "Socket operation on non-socket",                     // ENOTSOCK
    [87] = "Destination address required",                       // EDESTADDRREQ
    [88] = "Message too long",                                   // EMSGSIZE
    [89] = "Protocol wrong type for socket",                     // EPROTOTYPE
    [90] = "Protocol not available",                             // ENOPROTOOPT
    [91] = "Protocol not supported",                          // EPROTONOSUPPORT
    [92] = "Socket type not supported",                       // ESOCKTNOSUPPORT
    [93] = "Operation not supported",                         // ENOTSUP
    [94] = "Protocol family not supported",                   // EPFNOSUPPORT
    [95] = "Address family not supported by protocol",        // EAFNOSUPPORT
    [96] = "Address already in use",                          // EADDRINUSE
    [97] = "Cannot assign requested address",                 // EADDRNOTAVAIL
    [98] = "Network is down",                                 // ENETDOWN
    [99] = "Network is unreachable",                          // ENETUNREACH
    [100] = "Network dropped connection on reset",            // ENETRESET
    [101] = "Software caused connection abort",               // ECONNABORTED
    [102] = "Connection reset by peer",                       // ECONNRESET
    [103] = "No buffer space available",                      // ENOBUFS
    [104] = "Transport endpoint is already connected",        // EISCONN
    [105] = "Transport endpoint is not connected",            // ENOTCONN
    [106] = "Cannot send after transport endpoint shutdown",  // ESHUTDOWN
    [107] = "Too many references: cannot splice",             // ETOOMANYREFS
    [108] = "Connection timed out",                           // ETIMEDOUT
    [109] = "Connection refused",                             // ECONNREFUSED
    [110] = "Host is down",                                   // EHOSTDOWN
    [111] = "No route to host",                               // EHOSTUNREACH
    [112] = "Operation already in progress",                  // EALREADY
    [113] = "Operation now in progress",                      // EINPROGRESS
    [114] = "Stale file handle",                              // ESTALE
    [115] = "Structure needs cleaning",                       // EUCLEAN
    [116] = "Not a XENIX named type file",                    // ENOTNAM
    [117] = "No XENIX semaphores available",                  // ENAVAIL
    [118] = "Is a named type file",                           // EISNAM
    [119] = "Remote I/O error",                               // EREMOTEIO
    [120] = "Disk quota exceeded",                            // EDQUOT
    [121] = "No medium found",                                // ENOMEDIUM
    [122] = "Wrong medium type",                              // EMEDIUMTYPE
    [123] = "Operation canceled",                             // ECANCELED
    [124] = "Required key not available",                     // ENOKEY
    [125] = "Key has expired",                                // EKEYEXPIRED
    [126] = "Key has been revoked",                           // EKEYREVOKED
    [127] = "Key was rejected by service",                    // EKEYREJECTED
    [128] = "Owner died",                                     // EOWNERDEAD
    [129] = "State not recoverable",                          // ENOTRECOVERABLE
    [130] = "Operation not possible due to RF-kill",          // ERFKILL
    [131] = "Memory page has hardware error",                 // EHWPOISON
};
#endif
// для других систем массив ошибок не определяем

#endif